### ISSUE TITLE
draupnir-client fails to create correct config

### ISSUE THREAD

**Issue by nlopes** [gocardless/draupnir#34]
Steps to reproduce:
```
~ » rm ~/.draupnir
remove /Users/nlopes/.draupnir? y
~ » draupnir-client authenticate
error creating access token: Post https://set-me-to-a-real-domain/access_tokens: dial tcp: lookup set-me-to-a-real-domain: no such host
~ » vim ~/.draupnir # here I set domain to our internal production domain for draupnir
~ » draupnir-client authenticate
Successfully authenticated.
~ » cat ~/.draupnir
Domain = "<production draupnir domain>"
Database = ""

[Token]
  AccessToken = "<this populates with a correct token>"
  TokenType = "Bearer"
  RefreshToken = ""
  Expiry = 2018-01-25T11:10:45Z
~ » draupnir-client images list
error: Unauthorized (You do not have permission to view this resource)
```

**Comment by hmac** [comment]
The issue here is that the access token stored locally is an oauth refresh token, and once you lose it there's no way to get it back. Google doesn't let you re-authenticate and acquire a new refresh token (you'll only get a temporary access token if you re-authenticate). It's possible for draupnir to revoke the original authorisation and force Google to provide a new refresh token, but it doesn't currently do this.

Having an explicit step to revoke any existing authorisations as part of `draupnir-client authenticate` would probably be a good idea.

**Comment by nlopes** [comment]
This hasn't happened in later version so I'm going to close this.
